### ISSUE TITLE
[Feature] Limit pending edits per user

### ISSUE THREAD

**Issue by StashManRon** [stashapp/stash-box#805] opened 2024-08-15 00:31 UTC
(Copy of issue formerly known as #782 - Github have shadow banned me ....)

**Is your feature request related to a problem? Please describe.**

Currently users can submit an unlimited amount of concurrent edits regardless of experience/quality of submissions

**Describe the solution you'd like**

A maximum limit which is definable by admins. For further complication the limits could be definable by role and to further complicate, those with few successful edits only get say 5 pending edits and as they have more submissions successfully add then they can have more concurrent pending edits ...

**Describe alternatives you've considered**

Leaving it as is but in some cases this means the edit queues can get spammed/flooded

**Comment by DogmaDragon** [comment] 2024-12-07 21:19
Duplicate of https://github.com/stashapp/stash-box/issues/782

**Closed as not planned by DogmaDragon** 2024-12-07 21:19 UTC
Labels: duplicate, enhancement
