### ISSUE TITLE
[Bug Report] Invalid Height Does Not Create Error Warning

### ISSUE THREAD

**Issue by AdultSun** [stashapp/stash-box#626] opened 2023-03-13 00:10 UTC
**Describe the bug**
An invalid height that includes a decimal does not always create an "Invalid height" warning in the performer edit form. Values that are unreasonably high or unreasonably low create error messages but a decimal alone does not.

**To Reproduce**
1. Go to create a new performer
2. Fill the height field with "122.2"
3. No error message pops up
4. Clicking "Submit Edit" does nothing

**Expected behavior**
If the value is too high or too low, red "Invalid height" error messages appear in the "Personal Information" and "Confirm" tabs. The same error messages should appear when it contains a decimal but is still within a reasonable range.

**Screenshots**
![image](https://user-images.githubusercontent.com/64123896/224582523-ead60d9e-4d65-4cb4-a9f2-405aee36cea3.png)

**Additional context**
Tested with the PMVStash instance.

**Comment by SpedNSFW** [comment] 2023-03-15 10:41
Duplicate of #611

**Closed as completed** 2023-07-12 19:17 UTC
Labels: help wanted
